---
- hosts: aws_ec2
  connection: ssh
  become: yes
  user: ec2-user
  

  vars:
    ansible_ssh_private_key_file: "/etc/ansible/Myproject.pem"
    ansible_ssh_user: "ec2-user"

  tasks:

    - name: installing git
      action: yum name=git state=present

    - name: installing http
      yum: name=httpd state=present

    - name: restarting httpd
      service: name=httpd state=restarted

    - name: getting code from github
      git:
        url: "https://github.com/naveen4596/practise.git"
        dest: "/var/www/"
        version: "master"
